language: go
dist: trusty
sudo: required
before_install:
  - git clone --recursive git://github.com/apiaryio/drafter.git
  - cd drafter
  - git checkout v2.3.1
  - ./configure
  - make drafter
  - export PATH=$PWD/bin:$PATH
  - cd ..
install:
  - go get -d -t -v
script:
  - go test -v
